### PR TITLE
tracking_performances: Adjust axis extent

### PR DESCRIPTION
**Pull request by Simple-Shyam**
### Briefly, what does this PR introduce?
Minor fix in the code and range on the X axis is modified.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ x] Other: __
- minor fix in the code

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ x] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No
### Does this PR change default behavior?
No

### CODE REVIEW

**Comment by veprbl** [comment]
Just, FYI, the eicweb service is down this weekend, wel'll be able to test it no earlier than Monday.

**Comment by Simple-Shyam** [comment]
> Just, FYI, the eicweb service is down this weekend, wel'll be able to test it no earlier than Monday.

Thank you it's fine for me.

**Comment by Simple-Shyam** [comment]
> > Just, FYI, the eicweb service is down this weekend, wel'll be able to test it no earlier than Monday.
> 
> Thank you it's fine for me.

Is it finished?

**Comment by veprbl** [comment]
I've restarted the "Mirror and Trigger EICweb" to re-trigger the eicweb job. This has picked up now. Let's see.

**Comment by Simple-Shyam** [comment]
Thanks. I was thinking once it's done then I can mention in Thursday's tracking meeting and point to the artifacts.

**Comment by veprbl** [comment]
(We need to re-run with latest changes like https://github.com/eic/detector_benchmarks/pull/29, as your local branch wasn't including it.)

**Comment by veprbl** [comment]
It's ready btw. You can navigate "Show all checks", then "Details" for "eicweb/detector_benchmarks", then locate "collect_results:tracking_performance", open it, then "Browse" button on "Job artifacts" panel.

**Review by veprbl — APPROVED** [review]

**Comment by Simple-Shyam** [comment]
Thanks Dmitry, Now you can see the results for truth/real seeding is almost same except low momentum as I expect. 
In the plot linked below at 0.5 GeV/c, there is a point with a 0 value for this, I need to check 1D Gaussian  plot (What happened with Gaussian? ) once we store 1D debug plots directory. 
https://eicweb.phy.anl.gov/EIC/benchmarks/detector_benchmarks/-/jobs/3505085/artifacts/file/results/tracking_performances/mom_resol_-3.5_eta_-2.5.png

**Pull request merged**
