### PR TITLE
Muon insert

### PR DESCRIPTION
**Pull request by sebouh137**
### Briefly, what does this PR introduce?
benchmarks with muons in the insert. 

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [X] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [X] Tests for the changes have been added
- [X] Documentation has been added / updated
- [X] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
no
### Does this PR change default behavior?
no

### CODE REVIEW

**Comment by sebouh137** [comment]
why isn't this code in the master branch, even though it says it was merged?

**Comment by veprbl** [comment]
That's strange. Could be that merges instead of squashes don't mirror well to eicweb, then we probably need to disallow doing that.

**Comment by veprbl** [comment]
Can't blame eicweb probably. There is no pipeline on master with your merges: https://github.com/eic/detector_benchmarks/actions
Try squash merging next one.

**Comment by veprbl** [comment]
Let's try addressing in https://github.com/eic/detector_benchmarks/pull/72

**Pull request merged**
